### ISSUE TITLE
can i use this library with mkrethernet shield?

### ISSUE THREAD

**Issue by tradexsrl** [gregington/NetEEPROM#6]
can i use this library with a mkrgsm 1400+mkrethernet shield ?

**Comment by tradexsrl** [comment]
@juzam @gregington @per1234 please let me know

**Comment by per1234** [comment]
@tradexsrl [the MKR GSM 1400](https://store.arduino.cc/arduino-mkr-gsm-1400-1415) does not have EEPROM memory, so it is not compatible with this library.
